Retail_Bank_UI/Controllers/AdminController.cs
using AccountMicroservice.Model;
using CustomerMicroService.Model;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

using System.Threading.Tasks;

namespace Retail_Bank_UI.Controllers
{

    public class AdminController : Controller
    {

        public async Task<IActionResult> Index()
        {
            Client client = new Client();
            List<Account> accounts = new List<Account>();
            try
            {
                var result = await client.APIClient().GetAsync("https://localhost:44368/api/Account/getAllAccounts");
                if (result.IsSuccessStatusCode)
                {
                    var account = result.Content.ReadAsStringAsync().Result;
                    accounts = JsonConvert.DeserializeObject<List<Account>>(account);
                }
                return View(accounts);
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }
        }

       


    }

}

Retail_Bank_UI/Controllers/LoanUIController.cs
using CustomerMicroService.Model;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace Retail_Bank_UI.Controllers
{
    public class LoanUIController : Controller
    {
        int cd = CIDAll.cid;
        static int x;
        public async Task<IActionResult> AllLoans()
        {
            Client client = new Client();
            List<Loan> accounts = new List<Loan>();
            if(x==1)
            {
                ViewData["message"] = "Loan Request Accepted Successfully";
            }
            if (x == 2)
            {
                ViewData["message"] = "Loan Request Rejected Successfully";
            }
            try
            {
                var result = await client.APIClient().GetAsync("http://localhost:5004/api/Loan/getAllLoan");
                if (result.IsSuccessStatusCode)
                {
                    var data = result.Content.ReadAsStringAsync().Result;
                    var allLoans = JsonConvert.DeserializeObject<List<Loan>>(data);
                    return View(allLoans);
                }
                return View();
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }
        }


        [HttpGet]
        public async Task<IActionResult> Accept(int customerId)
        {
            Client client = new Client();
            List<Loan> accounts = new List<Loan>();
            try
            {
                var result = await client.APIClient().GetAsync("http://localhost:5004/api/Loan/Accept" + "/" + customerId);
                if (result.IsSuccessStatusCode)
                {
                    var data = result.Content.ReadAsStringAsync().Result;
                    x = 1;
                    return RedirectToAction("AllLoans");
                }

            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return Redirect("/Loan/AllLoans");
            }

            return Redirect("/Loan/AllLoans");
        }


        [HttpGet]
        public async Task<IActionResult> Reject(int CustomerId)
        {
            Client client = new Client();
            List<Loan> accounts = new List<Loan>();
            try
            {
                var result = await client.APIClient().GetAsync("http://localhost:5004/api/Loan/Reject" + "/" + CustomerId);
                if (result.IsSuccessStatusCode)
                {
                    var data = result.Content.ReadAsStringAsync().Result;
                    x = 2;
                    return RedirectToAction("AllLoans");

                }

            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return RedirectToAction("AllLoans");
            }

            return RedirectToAction("AllLoans");
        }


        [HttpGet]
        public async Task<IActionResult> LoanRequest()
        {
            
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> LoanRequest(Loan loanobj)
        {
            loanobj.CustomerId = cd;
            try
            {
                Client client = new Client();
                var res = await client.APIClient().PostAsJsonAsync("http://localhost:5004/api/Loan/CreateLoan", loanobj);
                if (res.IsSuccessStatusCode)
                {
                    ViewData["message"] = "Your Loan Request has placed Successfully";
                    return View();
                }
                ViewData["message"] = "Can't place your Loan Request";
                return View();
            }
            catch (Exception e)
            {
                ViewData["message"] = "Can't place your Loan Request";
               return View();
            }

        }


        [HttpGet]
        public async Task<IActionResult> CustomerLoans()
        {
            int CustomeId = cd;
            Client client = new Client();
            List<Loan> accounts = new List<Loan>();
            try
            {
                var result = await client.APIClient().GetAsync("http://localhost:5004/api/Loan/getCustomerLoan"+"/"+CustomeId);
                if (result.IsSuccessStatusCode)
                {
                    var data = result.Content.ReadAsStringAsync().Result;
                    var allLoans = JsonConvert.DeserializeObject<List<Loan>>(data);
                    return View(allLoans);
                }
                return View();
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }
        }

    }
}

Retail_Bank_UI/Controllers/LogInController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Retail_Bank_UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using UserMicroService.Models;

namespace Retail_Bank_UI.Controllers
{
    public class LogInController : Controller
    {
        public async Task<IEnumerable<UserCred>> GetAllUserAsync()
        {
            Client client = new Client();
            IEnumerable<UserCred> allCred = null;
            var result =await client.APIClient().GetAsync("/gateway/User/getAllUser");
            if(result.IsSuccessStatusCode)
            {
                var user = result.Content.ReadAsStringAsync().Result;
                allCred = JsonConvert.DeserializeObject<IEnumerable<UserCred>>(user);
            }
            return allCred;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Loginscreen()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Index(LogIn logIn)
        {
            IEnumerable<UserCred> userCreds =await GetAllUserAsync();

            TempData["UserName"] = logIn.Username;

            if (logIn.LogInType==UserType.Admin)
            {
                foreach (var item in userCreds)
                {
                    if(item.UserName==logIn.Username && item.Password==logIn.Password && item.UserType== "Admin")
                    {
                        var identity = new ClaimsIdentity(new[] {
                    new Claim(ClaimTypes.Name, logIn.Username),
                    new Claim(ClaimTypes.Role,"Admin")
                }, CookieAuthenticationDefaults.AuthenticationScheme);


                        ViewBag.Msg = "Successfully Logged In";
                        ModelState.Clear();
                         
                        return RedirectToAction("Index", "Admin");
                    }
                    ViewBag.Msg = "OOPS!!Wrong Credentials";
                }
               
            }
            else if(logIn.LogInType == UserType.Customer)
            {
                foreach (var item in userCreds)
                {
                    if (item.UserName == logIn.Username && item.Password == logIn.Password && item.UserType == "Customer")
                    {
                       var  identity = new ClaimsIdentity(new[] {
                    new Claim(ClaimTypes.Name, logIn.Username),
                    new Claim(ClaimTypes.Role,"Customer")
                }, CookieAuthenticationDefaults.AuthenticationScheme);

                        CIDAll.cid = (int) item.CustomerId;
                        ViewBag.Msg = "Successfully Logged In";
                        ModelState.Clear();
                        return RedirectToAction("Index","CustomerLogin",new {customerId= item.CustomerId });
                       
                    }
                    ViewBag.Msg = "OOPS!!Wrong Credentials";
                }
            }

        
            return View();
        }
    }
}

Retail_Bank_UI/Controllers/TransactionViewController.cs
using AccountMicroservice.Model;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Retail_Bank_UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using TransactionMicroservice.Models;

namespace Retail_Bank_UI.Controllers
{
    public class TransactionViewController : Controller
    {
        //trying-starts



        //trying-ends

        public List<Account> GetAllAccount()
        {
            Client client1 = new Client();
            List<Account> acc = new List<Account>();

            var result = client1.APIClient().GetAsync("https://localhost:44368/api/Account/getAllAccounts/").Result;
            if (result.IsSuccessStatusCode)
            {
                var s = result.Content.ReadAsStringAsync().Result;
                acc = JsonConvert.DeserializeObject<List<Account>>(s);
            }
            return acc;
        }

        public IActionResult Deposit()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult Deposit(Deposit _deposit)
        {
            TransactionStatus status = new TransactionStatus();
            List<Account> ac1 = new List<Account>();
            ac1 = GetAllAccount();
            foreach (var item in ac1)
            {
                if (item.Sav_AccountId == _deposit.AccountId)
                {
                    using (HttpClient client = new HttpClient())
                    {

                        client.BaseAddress = new Uri("http://localhost:5000/api/Transaction/");
                        client.DefaultRequestHeaders.Clear();
                        client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                        HttpResponseMessage response1 = client.PostAsJsonAsync("Deposit", _deposit).Result;
                        if (response1.IsSuccessStatusCode)
                        {
                            var s = response1.Content.ReadAsStringAsync().Result;
                            status = JsonConvert.DeserializeObject<TransactionStatus>(s);
                            ViewData["message"] = status.Message;


                        }
                        return View();
                    }
                }
            }
            ViewData["message"] = "Account Id not found";
            return View();
        }
        public IActionResult Withdraw()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Withdraw(Deposit _deposit)
        {
            TransactionStatus status = new TransactionStatus();
            List<Account> ac1 = new List<Account>();
            ac1 = GetAllAccount();
            foreach (var item in ac1)
            {
                if (item.Sav_AccountId == _deposit.AccountId)
                {
                    using (HttpClient client = new HttpClient())
                    {
                        client.BaseAddress = new Uri("http://localhost:5000/api/Transaction/");
                        client.DefaultRequestHeaders.Clear();
                        client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                        HttpResponseMessage response1 = client.PostAsJsonAsync("Withdraw", _deposit).Result;
                        if (response1.IsSuccessStatusCode)
                        {
                            var s = response1.Content.ReadAsStringAsync().Result;
                            status = JsonConvert.DeserializeObject<TransactionStatus>(s);
                            ViewData["message"] = status.Message;


                        }
                        return View();
                    }
                }
            }
            ViewData["message"] = "Account Id not valid";
            return View();
        }
        //Transfer
        public IActionResult Transfer()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Transfer(Transfer transfer)
        {
            TransactionStatus status = new TransactionStatus();
            List<Account> ac1 = new List<Account>();
            ac1 = GetAllAccount();
            foreach (var item in ac1)
            {
                
                    if (transfer.Source_ACC_ID == transfer.Destination_ACC_ID)
                    {
                        ViewData["message"] = "Source and Destination Account can't be same";
                        return View();
                    }

                        if (transfer.Destination_ACC_ID == item.Sav_AccountId)
                        {
                            using (HttpClient client = new HttpClient())
                            {

                                client.BaseAddress = new Uri("http://localhost:5000/api/Transaction/");
                                client.DefaultRequestHeaders.Clear();
                                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                                HttpResponseMessage response1 = client.PostAsJsonAsync("Transfer", transfer).Result;
                                if (response1.IsSuccessStatusCode)
                                {
                                    var s = response1.Content.ReadAsStringAsync().Result;
                                    status = JsonConvert.DeserializeObject<TransactionStatus>(s);
                                    ViewData["message"] = status.Message;
                                }
                                return View();
                            }
                        }
                    
                
            }
            ViewData["message"] = "Source or Destination Account not found";
            return View();
        }

        [HttpGet]
        public IActionResult GetStatement()
        {
            StatementUI sd = new StatementUI();
            return View(sd);
        }
        [HttpPost]
        public async Task<IActionResult> Statement(StatementUI sd)
        {
            List<Account> ac1 = new List<Account>();
            ac1 = GetAllAccount();
            foreach(var item in ac1)
            {
                if(item.Sav_AccountId==sd.AccountId)
                {
                    IEnumerable<Statement> status = null;

                    Client client = new Client();
                    var result = await client.APIClient().GetAsync("http://localhost:5000/api/Transaction/getStatement/" + sd.AccountId + "/" + sd.FromDate + "/" + sd.ToDate);
                    if (result.IsSuccessStatusCode)
                    {
                        var data = result.Content.ReadAsStringAsync().Result;
                        status = JsonConvert.DeserializeObject<IEnumerable<Statement>>(data);
                    }
                    return View(status);
                }
            }
            return RedirectToAction("GetStatement");
           
        }


    }
    }

Retail_Bank_UI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - project</title>
    <link href="~/images/SRF logo2.jpg" rel="icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Mysite.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark navbar-survival101">
            <div class="container">
                <a class="navbar-brand font-weight-bolder" asp-action="Index">
                    SRF Bank
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active ">
                            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">All Accounts</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" asp-area="" asp-controller="CreateCustomerAccount" asp-action="Index">Create Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="LoanUI" asp-action="AllLoans">All Loan Requests</a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link" asp-area="" asp-controller="TransactionView" asp-action="Deposit">Deposit</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" asp-area="" asp-controller="TransactionView" asp-action="Withdraw">Withdraw</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" asp-area="" asp-controller="TransactionView" asp-action="Transfer">Transfer</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" asp-area="" asp-controller="LogIn" asp-action="Index">Logout</a>
                        </li>


                    </ul>

                </div>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main">
            <div class="border-dark" style="height:80px">
                <br />
                <div>
                    <h4 style="text-align: right; color: #2b6dad;"><b> Welcome Admin @TempData["UserName"] </b></h4>
                </div>
                
            </div>
            @RenderBody()
            <div style="height:40px">

            </div>

        </main>
    </div>
    

    <footer class="border-top footer text-muted " style="background-color: #2b6dad">
        <div class="container text-light">
            &copy; 2022 SRF Bank Designed and Developed by POD-D
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Retail_Bank_UI/Views/Shared/_CustomerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - project</title>
    <link href="~/images/SRF logo2.jpg" rel="icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Mysite.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark navbar-survival101">
            <div class="container">
                <a class="navbar-brand font-weight-bolder" asp-action="Index">
                    SRF Bank
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active ">
                            <a class="nav-link" asp-area="" asp-controller="CustomerLogin" asp-action="Index">My Account</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="LoanUI" asp-action="LoanRequest">Loan Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="LoanUI" asp-action="CustomerLoans">Loan Status</a>
                        </li>
                        @*<li class="nav-item ">
                            <a class="nav-link" asp-area="" asp-controller="CustomerLogin" asp-action="DepositCustomer">Deposit</a>
                        </li>*@
                        @*<li class="nav-item ">
                            <a class="nav-link" asp-area="" asp-controller="CustomerLogin" asp-action="WithdrawCustomer">Withdraw</a>
                        </li>*@
                        <li class="nav-item ">
                            <a class="nav-link" asp-area="" asp-controller="CustomerLogin" asp-action="TransferCustomer">Transfer</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" asp-area="" asp-controller="CustomerLogin" asp-action="GetStatementCustomer">Statement</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" asp-area="" asp-controller="LogIn" asp-action="Index">Logout</a>
                        </li>


                    </ul>

                </div>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main">
            <div class="border-dark" style="height:80px">
                <br />
                <div>
                    <h4 style="text-align: right; color: #2b6dad;"><b> Welcome Customer @TempData["UserName"] </b></h4>
                </div>

            </div>
          

            @RenderBody()
         

        </main>
    </div>

    <footer class="border-top footer text-muted " style="background-color: #2b6dad">
        <div class="container text-light">
            &copy; 2022 SRF Bank Designed and Developed by POD-D
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Retail_Bank_UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RetailBank_UI</title>
    <link href="~/images/SRF logo2.jpg" rel="icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Mysite.css" />
    <style>
        body{
            height:600px;
        }

    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark navbar-survival101">
            <div class="container">
                <a class="navbar-brand font-weight-bolder" asp-action="Index">
                    SRF Bank
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active ml-3 mr-3">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item ml-auto mr-3 ml-3">
                            <a class="nav-link" asp-controller="Login" asp-action="Index">Loan</a>
                        </li>
                        <li class="nav-item ml-auto mx-3">
                            <a class="nav-link" asp-controller="Login" asp-action="index">Banking</a>
                        </li>
                        <li class="nav-item ml-auto mx-3">
                            <a class="nav-link" asp-controller="Login" asp-action="Index">Account</a>
                        </li>
                        <li class="nav-item ml-auto mx-3">
                            <a class="nav-link" asp-controller="Login" asp-action="Index">Offers</a>
                        </li>
                        

                        <a class="btn btn-outline-light" asp-controller="Login" asp-action="Index">Login</a>
                    </ul>
                    @*<form class="form-inline">
                            <div class="input-group search-box">
                                <input type="text" class="form-control" placeholder="What are you looking for?" aria-label="Search for...">
                                <span class="input-group-btn">
                                    <button class="btn btn-secondary" type="button"><i class="ion-search"></i></button>
                                </span>
                            </div>
                        </form>*@
                </div>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-5">
            <div style="height:40px">

            </div>
            @RenderBody()


        </main>
    </div>



    <footer class="border-top footer text-muted " style="background-color: #2b6dad">
        <div class="container text-light">
            &copy; 2022 SRF Bank Designed and Developed by POD-D
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>