Retail_Bank_UI/Controllers/CustomerDetailsController.cs
using AccountMicroservice.Model;
using CustomerMicroService.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Retail_Bank_UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using TransactionMicroservice.Models;

namespace Retail_Bank_UI.Controllers
{

    public class CustomerDetailsController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index(int customerId)
        {
            Client client = new Client();
            Customer customer = new Customer();

            List<Account> accounts = new List<Account>();
            try
            {


                var result = await client.APIClient().GetAsync("/gateway/Customer/getCustomerDetails/" + customerId);
                var apiAcc = await client.APIClient().GetAsync("https://localhost:44368/api/Account/getCustomerAccount/" + customerId);
                if (result.IsSuccessStatusCode)
                {
                    var user = result.Content.ReadAsStringAsync().Result;
                    customer = JsonConvert.DeserializeObject<Customer>(user);
                }
                if (apiAcc.IsSuccessStatusCode)
                {
                    var account = apiAcc.Content.ReadAsStringAsync().Result;
                    accounts = JsonConvert.DeserializeObject<List<Account>>(account);

                    ViewData["AccountInfo"] = accounts;
                }

                return View(customer);
            }
            catch(Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }
        }
        



        public IActionResult Statement(int AccountId)
        {
            ViewBag.AccountId = AccountId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Statement(int AccountId, StatementUI statement)
        {
            Client client = new Client();
            List<Statement> statements = new List<Statement>();
            statement.AccountId = AccountId;
            try
            {
                var result = await client.APIClient().GetAsync("/gateway/Transaction/getStatement/" + statement.AccountId + "/" + statement.FromDate.ToString("yyyy-MM-dd HH:mm:ss") + "/" + statement.ToDate.ToString("yyyy-MM-dd HH:mm:ss"));
                if (result.IsSuccessStatusCode)
                {
                    var s = result.Content.ReadAsStringAsync().Result;
                    statements = JsonConvert.DeserializeObject<List<Statement>>(s);
                }
                return View("StatementDetails", statements);
            }
            catch(Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }
        }


    }
}

Retail_Bank_UI/Controllers/CustomerLoginController.cs
using AccountMicroservice.Model;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Retail_Bank_UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using TransactionMicroservice.Models;

namespace Retail_Bank_UI.Controllers
{
    public class CustomerLoginController : Controller
    {

        public async Task<IActionResult> Index(int customerId)
        {
            if (customerId == 0)
            {
                customerId = CIDAll.cid;
            }
            Client client = new Client();
            List<Account> accounts = new List<Account>();
            try
            {
                var result = await client.APIClient().GetAsync("https://localhost:44368/api/Account/getCustomerAccount" + "/" + customerId);
                if (result.IsSuccessStatusCode)
                {
                    var account = result.Content.ReadAsStringAsync().Result;
                    accounts = JsonConvert.DeserializeObject<List<Account>>(account);
                }
                return View(accounts);
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }

        }

        public IActionResult DepositCustomer()
        {
            Deposit dp = new Deposit();
            List<Account> accounts = GetAccountId();
            dp.AccountId = accounts[0].Sav_AccountId;
            return View(dp);
        }


        public List<Account> GetAccountId()
        {
            Client client1 = new Client();
            List<Account> acc = new List<Account>();

            var result = client1.APIClient().GetAsync("https://localhost:44368/api/Account/getCustomerAccount/" + CIDAll.cid).Result;
            if (result.IsSuccessStatusCode)
            {
                var s = result.Content.ReadAsStringAsync().Result;
                acc = JsonConvert.DeserializeObject<List<Account>>(s);
            }
            return acc;
        }


        public List<Account> GetAllAccount()
        {
            Client client1 = new Client();
            List<Account> acc = new List<Account>();

            var result = client1.APIClient().GetAsync("https://localhost:44368/api/Account/getAllAccounts/").Result;
            if (result.IsSuccessStatusCode)
            {
                var s = result.Content.ReadAsStringAsync().Result;
                acc = JsonConvert.DeserializeObject<List<Account>>(s);
            }
            return acc;
        }


        [HttpPost]
        public IActionResult DepositCustomer(Deposit _deposit)
        {

            List<Account> ac = GetAccountId();

            _deposit.AccountId = ac[0].Sav_AccountId;
            TransactionStatus status = new TransactionStatus();

            using (HttpClient client = new HttpClient())
            {

                client.BaseAddress = new Uri("http://localhost:5000/api/Transaction/");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response1 = client.PostAsJsonAsync("Deposit", _deposit).Result;
                if (response1.IsSuccessStatusCode)
                {
                    var s = response1.Content.ReadAsStringAsync().Result;
                    status = JsonConvert.DeserializeObject<TransactionStatus>(s);
                    ViewData["message"] = status.Message;


                }
                return View();
            }
        }

        public IActionResult WithdrawCustomer()
        {
            Deposit dp = new Deposit();
            List<Account> accounts = GetAccountId();
            dp.AccountId = accounts[0].Sav_AccountId;
            return View(dp);

        }
        [HttpPost]
        public IActionResult WithdrawCustomer(Deposit _deposit)
        {
            TransactionStatus status = new TransactionStatus();

            using (HttpClient client = new HttpClient())
            {

                client.BaseAddress = new Uri("http://localhost:5000/api/Transaction/");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response1 = client.PostAsJsonAsync("Withdraw", _deposit).Result;
                if (response1.IsSuccessStatusCode)
                {
                    var s = response1.Content.ReadAsStringAsync().Result;
                    status = JsonConvert.DeserializeObject<TransactionStatus>(s);
                    ViewData["message"] = status.Message;


                }
                return View();
            }
        }


        public IActionResult TransferCustomer()
        {
            Transfer transfer = new Transfer();
            List<Account> accounts = GetAccountId();
            transfer.Source_ACC_ID = accounts[0].Sav_AccountId;
            return View(transfer);
        }
        [HttpPost]
        public IActionResult TransferCustomer(Transfer transfer)
        {
            TransactionStatus status = new TransactionStatus();
            List<Account> ac1 = new List<Account>();
            ac1 = GetAllAccount();
            foreach (var item in ac1)
            {
                if (item.Sav_AccountId == transfer.Destination_ACC_ID)
                {
                    using (HttpClient client = new HttpClient())
                    {

                        client.BaseAddress = new Uri("http://localhost:5000/api/Transaction/");
                        client.DefaultRequestHeaders.Clear();
                        client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                        HttpResponseMessage response1 = client.PostAsJsonAsync("Transfer", transfer).Result;
                        if (response1.IsSuccessStatusCode)
                        {
                            var s = response1.Content.ReadAsStringAsync().Result;
                            status = JsonConvert.DeserializeObject<TransactionStatus>(s);
                            ViewData["message"] = status.Message;


                        }
                        return View();
                    }
                }
            }
            ViewData["message"] = "Destination account not found !!";

            return View();

        }
    

        [HttpGet]
        public IActionResult GetStatementCustomer()
        {
            StatementUI sd = new StatementUI();
            List<Account> accounts = GetAccountId();
            sd.AccountId = accounts[0].Sav_AccountId;
            return View(sd);
        }
        [HttpPost]
        public async Task<IActionResult> StatementCustomer(StatementUI sd)
        {

            IEnumerable<Statement> status = null;

            Client client = new Client();
            var result = await client.APIClient().GetAsync("http://localhost:5000/api/Transaction/getStatement/" + sd.AccountId + "/" + sd.FromDate + "/" + sd.ToDate);
            if (result.IsSuccessStatusCode)
            {
                var data = result.Content.ReadAsStringAsync().Result;
                status = JsonConvert.DeserializeObject<IEnumerable<Statement>>(data);
            }
            return View(status);
        }

    }
}

Retail_Bank_UI/Views/CustomerLogin/DepositCustomer.cshtml
@model TransactionMicroservice.Models.Deposit

@{ ViewData["Title"] = "Deposit";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml"; }

<head>

    <style>
        body {
            height: 600px;
        }
        .demo {
            font-family: 'Noto Sans', sans-serif;
        }

        .panel {
            background: linear-gradient(to right, #2980b9, #2c3e50);
            padding: 0;
            border-radius: 10px;
            border: none;
            box-shadow: 0 0 0 5px rgba(0,0,0,0.05),0 0 0 10px rgba(0,0,0,0.05);
        }

            .panel .panel-heading {
                padding: 20px 15px;
                border-radius: 10px 10px 0 0;
                margin: 0;
            }

                .panel .panel-heading .title {
                    color: #fff;
                    font-size: 28px;
                    font-weight: 500;
                    text-transform: capitalize;
                    line-height: 40px;
                    margin: 0;
                }

                .panel .panel-heading .btn {
                    color: rgba(255,255,255,0.5);
                    background: transparent;
                    font-size: 16px;
                    text-transform: capitalize;
                    border: 2px solid #fff;
                    border-radius: 50px;
                    transition: all 0.3s ease 0s;
                }

                    .panel .panel-heading .btn:hover {
                        color: #fff;
                        text-shadow: 3px 3px rgba(255,255,255,0.2);
                    }

                .panel .panel-heading .form-control {
                    color: #fff;
                    background-color: transparent;
                    width: 35%;
                    height: 40px;
                    border: 2px solid #fff;
                    border-radius: 20px;
                    display: inline-block;
                    transition: all 0.3s ease 0s;
                }

                    .panel .panel-heading .form-control:focus {
                        background-color: rgba(255,255,255,0.2);
                        box-shadow: none;
                        outline: none;
                    }

                    .panel .panel-heading .form-control::placeholder {
                        color: rgba(255,255,255,0.5);
                        font-size: 15px;
                        font-weight: 500;
                    }

            .panel .panel-body {
                padding: 0;
            }

                .panel .panel-body .table thead tr th {
                    color: #fff;
                    background-color: rgba(255, 255, 255, 0.2);
                    font-size: 16px;
                    font-weight: 500;
                    text-transform: uppercase;
                    padding: 12px;
                    border: none;
                }

                .panel .panel-body .table tbody tr td {
                    color: #fff;
                    font-size: 15px;
                    padding: 10px 12px;
                    vertical-align: middle;
                    border: none;
                }

                .panel .panel-body .table tbody tr:nth-child(even) {
                    background-color: rgba(255,255,255,0.05);
                }

                .panel .panel-body .table tbody .action-list {
                    padding: 0;
                    margin: 0;
                    list-style: none;
                }

                    .panel .panel-body .table tbody .action-list li {
                        display: inline-block;
                        margin: 0 5px;
                    }

                        .panel .panel-body .table tbody .action-list li a {
                            color: #fff;
                            font-size: 15px;
                            position: relative;
                            z-index: 1;
                            transition: all 0.3s ease 0s;
                        }

                            .panel .panel-body .table tbody .action-list li a:hover {
                                text-shadow: 3px 3px 0 rgba(255,255,255,0.3);
                            }

                            .panel .panel-body .table tbody .action-list li a:before,
                            .panel .panel-body .table tbody .action-list li a:after {
                                content: attr(data-tip);
                                color: #fff;
                                background-color: #111;
                                font-size: 12px;
                                padding: 5px 7px;
                                border-radius: 4px;
                                text-transform: capitalize;
                                display: none;
                                transform: translateX(-50%);
                                position: absolute;
                                left: 50%;
                                top: -32px;
                                transition: all 0.3s ease 0s;
                            }

                            .panel .panel-body .table tbody .action-list li a:after {
                                content: '';
                                height: 15px;
                                width: 15px;
                                padding: 0;
                                border-radius: 0;
                                transform: translateX(-50%) rotate(45deg);
                                top: -18px;
                                z-index: -1;
                            }

                            .panel .panel-body .table tbody .action-list li a:hover:before,
                            .panel .panel-body .table tbody .action-list li a:hover:after {
                                display: block;
                            }

            .panel .panel-footer {
                color: #fff;
                background-color: transparent;
                padding: 15px;
                border: none;
            }

                .panel .panel-footer .col {
                    line-height: 35px;
                }

        .pagination {
            margin: 0;
        }

            .pagination li a {
                color: #fff;
                background-color: transparent;
                border: 2px solid transparent;
                font-size: 18px;
                font-weight: 500;
                text-align: center;
                line-height: 31px;
                width: 35px;
                height: 35px;
                padding: 0;
                margin: 0 3px;
                border-radius: 50px;
                transition: all 0.3s ease 0s;
            }

                .pagination li a:hover {
                    color: #fff;
                    background-color: transparent;
                    border-color: rgba(255,255,255,0.2);
                }

                .pagination li a:focus,
                .pagination li.active a,
                .pagination li.active a:hover {
                    color: #fff;
                    background-color: transparent;
                    border-color: #fff;
                }

            .pagination li:first-child a,
            .pagination li:last-child a {
                border-radius: 50%;
            }
    </style>
</head>

<div>
    <div>

        <div class="row align-items-center">
            <div class="col-md-offset-1 col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col text-light">
                                <h1 class="text-center">Deposit</h1>
                            </div>

                        </div>
                    </div>



                    <div class="align-items-center text-center">
                        <h4 class="text-light">@ViewData["message"]</h4>
                    </div>

                    <hr />


                    <div class="container">
                        <div class="row h-100 justify-content-center align-items-center">
                            <div class="col-md-4">
                                <form asp-action="DepositCustomer">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group text-light">
                                        <label asp-for="AccountId" class="control-label"></label>
                                        <input asp-for="AccountId" class="form-control " readonly/>
                                        <span asp-validation-for="AccountId" class="text-danger"></span>
                                    </div>
                                    <div class="form-group text-light is-valid">
                                        <label asp-for="Amount" class="control-label">Amount</label>
                                        <input asp-for="Amount" class="form-control" type="number" min="1" max="1000000"  pattern="[0-9]{1,7}" title="Invalid amount" />
                                        <span asp-validation-for="Amount" class="text-danger"></span>
                                    </div>
                                    <div class="form-group text-light">
                                        <input type="submit" value="Deposit" class="btn btn-sm border border-light" />
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
</div>

Retail_Bank_UI/Views/CustomerLogin/Index.cshtml
@model IEnumerable<AccountMicroservice.Model.Account>

@{ ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml"; }
<head>
    <link rel="stylesheet" href="~/css/Mysite.css" />
    <style>
        body{
            height:600px;
        }
        .demo {
            font-family: 'Noto Sans', sans-serif;
        }

        .panel {
            background: linear-gradient(to right, #2980b9, #2c3e50);
            padding: 0;
            border-radius: 10px;
            border: none;
            box-shadow: 0 0 0 5px rgba(0,0,0,0.05),0 0 0 10px rgba(0,0,0,0.05);
        }

            .panel .panel-heading {
                padding: 20px 15px;
                border-radius: 10px 10px 0 0;
                margin: 0;
            }

                .panel .panel-heading .title {
                    color: #fff;
                    font-size: 28px;
                    font-weight: 500;
                    text-transform: capitalize;
                    line-height: 40px;
                    margin: 0;
                }

                .panel .panel-heading .btn {
                    color: rgba(255,255,255,0.5);
                    background: transparent;
                    font-size: 16px;
                    text-transform: capitalize;
                    border: 2px solid #fff;
                    border-radius: 50px;
                    transition: all 0.3s ease 0s;
                }

                    .panel .panel-heading .btn:hover {
                        color: #fff;
                        text-shadow: 3px 3px rgba(255,255,255,0.2);
                    }

                .panel .panel-heading .form-control {
                    color: #fff;
                    background-color: transparent;
                    width: 35%;
                    height: 40px;
                    border: 2px solid #fff;
                    border-radius: 20px;
                    display: inline-block;
                    transition: all 0.3s ease 0s;
                }

                    .panel .panel-heading .form-control:focus {
                        background-color: rgba(255,255,255,0.2);
                        box-shadow: none;
                        outline: none;
                    }

                    .panel .panel-heading .form-control::placeholder {
                        color: rgba(255,255,255,0.5);
                        font-size: 15px;
                        font-weight: 500;
                    }

            .panel .panel-body {
                padding: 0;
            }

                .panel .panel-body .table thead tr th {
                    color: #fff;
                    background-color: rgba(255, 255, 255, 0.2);
                    font-size: 16px;
                    font-weight: 500;
                    text-transform: uppercase;
                    padding: 12px;
                    border: none;
                }

                .panel .panel-body .table tbody tr td {
                    color: #fff;
                    font-size: 15px;
                    padding: 10px 12px;
                    vertical-align: middle;
                    border: none;
                }

                .panel .panel-body .table tbody tr:nth-child(even) {
                    background-color: rgba(255,255,255,0.05);
                }

                .panel .panel-body .table tbody .action-list {
                    padding: 0;
                    margin: 0;
                    list-style: none;
                }

                    .panel .panel-body .table tbody .action-list li {
                        display: inline-block;
                        margin: 0 5px;
                    }

                        .panel .panel-body .table tbody .action-list li a {
                            color: #fff;
                            font-size: 15px;
                            position: relative;
                            z-index: 1;
                            transition: all 0.3s ease 0s;
                        }

                            .panel .panel-body .table tbody .action-list li a:hover {
                                text-shadow: 3px 3px 0 rgba(255,255,255,0.3);
                            }

                            .panel .panel-body .table tbody .action-list li a:before,
                            .panel .panel-body .table tbody .action-list li a:after {
                                content: attr(data-tip);
                                color: #fff;
                                background-color: #111;
                                font-size: 12px;
                                padding: 5px 7px;
                                border-radius: 4px;
                                text-transform: capitalize;
                                display: none;
                                transform: translateX(-50%);
                                position: absolute;
                                left: 50%;
                                top: -32px;
                                transition: all 0.3s ease 0s;
                            }

                            .panel .panel-body .table tbody .action-list li a:after {
                                content: '';
                                height: 15px;
                                width: 15px;
                                padding: 0;
                                border-radius: 0;
                                transform: translateX(-50%) rotate(45deg);
                                top: -18px;
                                z-index: -1;
                            }

                            .panel .panel-body .table tbody .action-list li a:hover:before,
                            .panel .panel-body .table tbody .action-list li a:hover:after {
                                display: block;
                            }

            .panel .panel-footer {
                color: #fff;
                background-color: transparent;
                padding: 15px;
                border: none;
            }

                .panel .panel-footer .col {
                    line-height: 35px;
                }

        .pagination {
            margin: 0;
        }

            .pagination li a {
                color: #fff;
                background-color: transparent;
                border: 2px solid transparent;
                font-size: 18px;
                font-weight: 500;
                text-align: center;
                line-height: 31px;
                width: 35px;
                height: 35px;
                padding: 0;
                margin: 0 3px;
                border-radius: 50px;
                transition: all 0.3s ease 0s;
            }

                .pagination li a:hover {
                    color: #fff;
                    background-color: transparent;
                    border-color: rgba(255,255,255,0.2);
                }

                .pagination li a:focus,
                .pagination li.active a,
                .pagination li.active a:hover {
                    color: #fff;
                    background-color: transparent;
                    border-color: #fff;
                }

            .pagination li:first-child a,
            .pagination li:last-child a {
                border-radius: 50%;
            }
    </style>
</head>

<div>
    <div class="container justify-content-sm-center align-items-center">

        <div class="row align-items-center">
            <div class="col-md-offset-1 col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col col-sm-3 col-xs-12">
                                <h4 class="title">Account <span>Details</span></h4>
                            </div>

                        </div>
                    </div>
                    <div class="panel-body table-responsive">
                        <table class="table">
                            <thead>
                                <tr>

                                    <th>
                                        @Html.DisplayNameFor(model => model.CustomerId)
                                    </th>
                                    <th>
                                        Account Number
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.accountType)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Balance)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.MinBalance)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                    <tr>
                       
                        <td class="text-center ">
                            <a asp-controller="CustomerDetails" asp-action="Index" asp-route-CustomerId="@item.CustomerId" class="text-light">
                                @Html.DisplayFor(modelItem => item.CustomerId)
                            </a>
                        </td>

                        <td>
                            @if (item.Cur_AccountId == 0)
                            {
            @Html.DisplayFor(modelItem => item.Sav_AccountId) }
        else
        {
@Html.DisplayFor(modelItem => item.Cur_AccountId)}
                            @*<a asp-controller="CustomerDetails" asp-action="Index" asp-route-AccountId="@item.Sav_AccountId">
                                    @Html.DisplayFor(modelItem => item.Sav_AccountId)
                                </a>*@
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.accountType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Balance)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MinBalance)
                        </td>


                    </tr>
}
                            </tbody>
                        </table>
                    </div>
             
                </div>
            </div>
        </div>

    </div>
</div>